import React from 'react'

const About = () => {
    return(
        <div className="container text-danger">
           <p>Development of applications with leading edge tools and technologiesDevelopment of applications with leading edge tools and technologiesDevelopment of applications with leading edge tools and technologiesDevelopment of applications with leading edge tools and technologiesDevelopment of applications with leading edge tools and technologiesDevelopment of applications with leading edge tools and technologiesDevelopment of applications with leading edge tools and technologiesDevelopment of applications with leading edge tools and technologiesDevelopment of applications with leading edge tools and technologiesDevelopment of applications with leading edge tools and technologiesDevelopment of applications with leading edge tools and technologiesDevelopment of applications with leading edge tools and technologiesDevelopment of applications with leading edge tools and technologiesDevelopment of applications with leading edge tools and technologies</p>
           <p>Development of applications with leading edge tools and technologiesDevelopment of applications with leading edge tools and technologiesDevelopment of applications with leading edge tools and technologiesDevelopment of applications with leading edge tools and technologiesDevelopment of applications with leading edge tools and technologiesDevelopment of applications with leading edge tools and technologiesDevelopment of applications with leading edge tools and technologiesDevelopment of applications with leading edge tools and technologiesDevelopment of applications with leading edge tools and technologiesDevelopment of applications with leading edge tools and technologiesDevelopment of applications with leading edge tools and technologiesDevelopment of applications with leading edge tools and technologiesDevelopment of applications with leading edge tools and technologiesDevelopment of applications with leading edge tools and technologies</p>
           <p>Development of applications with leading edge tools and technologiesDevelopment of applications with leading edge tools and technologiesDevelopment of applications with leading edge tools and technologiesDevelopment of applications with leading edge tools and technologiesDevelopment of applications with leading edge tools and technologiesDevelopment of applications with leading edge tools and technologiesDevelopment of applications with leading edge tools and technologiesDevelopment of applications with leading edge tools and technologiesDevelopment of applications with leading edge tools and technologiesDevelopment of applications with leading edge tools and technologiesDevelopment of applications with leading edge tools and technologiesDevelopment of applications with leading edge tools and technologiesDevelopment of applications with leading edge tools and technologiesDevelopment of applications with leading edge tools and technologies</p>
        </div>
    );
}

export default About;